<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReflectGov.Application\ReflectGov.Application.csproj" />
    <ProjectReference Include="..\ReflectGov.Infrastructure\ReflectGov.Infrastructure.csproj" />
    <ProjectReference Include="..\ReflectGov.Domain\ReflectGov.Domain.csproj" />
  </ItemGroup>

</Project>
